### PR TITLE
Added MCM support

### PR DESCRIPTION
**Pull request by BernardoCBranco**

### CODE REVIEW

**Comment by Luminger** [comment]
Thanks for your contribution, having MCM support is a very nice addition I wanted to have for a long time but couldn't find the time to add it myself.

It looks like you're still testing/working on this PR; just let me know when it's ready from your point and I'll have a look.

**Comment by BernardoCBranco** [comment]
It's pretty much done, the functionality is there although there is still something that I wanted to do. It's possible to change the settings mid mission but the changes won't take effect until the next one. I tried to figure out how to make them immediate but had limited success, only managed to make some of them work correctly and ended giving up and simply locking everything during missions. I will try again to make it work but if not I'll enable those that worked previously and maybe leave a warning for the rest.

**Comment by BernardoCBranco** [comment]
Managed to make any setting changes mid mission take effect immediately, had to move a few things around and it's probably not the cleanest solution but it works. I also noticed a glitch that sometimes happens when returning from tactical, I'm pretty sure the cause is this [issue](https://github.com/andrewgu/ModConfigMenu/issues/39) from MCM but I'll see if there's something I can do.

**Comment by BernardoCBranco** [comment]
Found the problem, I was storing references to MCM stuff as instance variables inside the settings listener which was causing the glitch. I saw the warning about the UIScreen and UIPanel but completely forgot that MCM also extends those classes -_-'.  The listener is now separate and just creates a new instance of the settings class. It should be fine merge now.

**Comment by Luminger** [comment]
I'm sorry that it takes so long for me to have a look at this change, I'll see that I have a look at it soonish. Just wanted to leave you a note that I'm still interested in this change =)

**Comment by BernardoCBranco** [comment]
It's ok, I haven't had the time to take a better look at it either. From what I tested it seems to be working fine, however I'm not exactly satisfied with how I did some stuff but it was the only way I found to make some things work, there probably is a better solution but I'm not sure what. I would really appreciate your opinion on this.

**Comment by Luminger** [comment]
Would be cool if you could point out the things you weren't sure about.
Would make it easier for me to reason about them :)

I think I spotted a minor logic defect somewhere regarding the different
'show me this but not that' options. But it wasn't a big deal afair, I'll
see that I get all that tested.

**Comment by Luminger** [comment]
Finally, I found some time reading through the changes.

I'm very happy you changed things to the better, thanks for cleaning things up while adding new functionality as well!

I have some objections regarding the code duplication we now have in KillCounter_UI::Update and KillCounter::UpdateUI. I think that was initially my (bad) design, but now it seems obvious that the main `KillCounter` class shouldn't know anything about the UI. I'll see if I can move that stuff into the `KillCounter_UI` class.

Also, I'm a little concerned about the possible overhead generated by the calls to `class'KillCounter_Utils'.static.Should*` as it involves getting a new `KillCounter_Settings` object whenever those are called, and they are potentially called a lot as they are usually called all together and, when there's a lot going on, the `UpdateUI` method is called a couple times a second at times. It might be an easy win to reuse a `Settings` object here whenever possible. I'll see if I can move things around (those static methods might belong into the newly created `KillCounter_Settings` class as methods, as they solely act on that object) which might make it a little cleaner.

Even though I haven't playtested it by now, I'm very happy with it. I like it a lot when things get cleaner on the way, and your PR is a very good example of the campground rule! Thank's again!

**Comment by Luminger** [comment]
I managed to get some changes done yesterday evening, I've created a new PR #6. Would be cool if you could have a look if I broke anything obvious.

My very limited playtest showed no defects, but more testing is still needed.

**Comment by BernardoCBranco** [comment]
Sorry it took me a while to answer, I found two issues with those changes, one is easy to fix while the other one I'm not sure. The first one is that every time the settings change KillCounter_UI::Update also needs to be called, otherwise some changes won't take effect. The second is that when loading a tactical save while in tactical sometimes the counter won't reappear, I actually had already made the changes you recommended but I didn't commit them because I was having that same issue, that one I'm not sure what's causing it.

**Comment by Luminger** [comment]
No worries, I'm quite bad with responding on my own - a couple hours/days is fine ;)

The first issue is easy, correct - I've reordered some stuff and a call to `KillCounter_UI::UpdateSettings` will now also call `KillCounter_UI::Update` (commit will follow soon).

I've noticed the second issue you described from time to time as well, but I wasn't able to find a root cause of this and it vanished on the next mission start/load; usually that just happened when I tried a broken development version, so it never occurred to me that this is a general problem. I'll see if I can isolate that issue when I load a tactical game (thanks for the hint!).

**Comment by Luminger** [comment]
Sometimes this mod is too sensitive to minor changes... I could figure out why the UI isn't shown on a savegame load; The UI was never initialized when a game was loaded, so I added a call to `KillCounter_Utils::GetUI` to get things going. This fixed that bug, but the values then never updated, the counters were stuck.

Guess I have to debug this further, but I ran out of time this morning. I'll see that I get some work done in the evening.

**Comment by BernardoCBranco** [comment]
Found the issue to why it stops updating, although I'm still not sure why it's not working. Changing `LastRealizedIndex = default.LastRealizedIndex;` to `LastRealizedIndex = -1;` fixes it. -_-'

EDIT: I originally thought that when they said "[The default value for a class variable can be accessed directly by using the keyword default and the context operator '.' from anywhere inside the class](https://wiki.beyondunreal.com/Variables#Accessing_variables)" they meant the values defined in `defaultproperties` but that's not the case, I'm confused about what they mean by "default value", it's just returning the current variable value.

EDIT2: Now I'm even more confused, it's working as intended in `KillCounter_UI` but for some reason not in `KillCounter`.

**Comment by Luminger** [comment]
You're right, I can confirm your observations (I made them as well without knowing you edited your comment). I even read the same document you quoted and was equally confused about that statement and actual behavior in this case.

It might be safer to just revert the `default.foobar` assignments back to a duplicated hardcoded value, just in case things start to get weird in the future again.

Edit: I updated my branch and pushed fixes for both issues.
Edit^2: I think I'm fine with the code for now; Unless you have any objections I'm fine merging and releasing it as well in the next days (after more in-depth playtesting).

**Comment by BernardoCBranco** [comment]
Sure, it's fine by me, I'll also test it a bit more tomorrow but so far I haven't found any other issue.

**Comment by Luminger** [comment]
Once again, thanks for your hard work! The PR is now merged and the mod already updated in the Workshop!

**Pull request merged**
